"""milestone table created

Revision ID: 4b1318f2d822
Revises: d1f5dfae3cda
Create Date: 2026-06-24 20:51:01.016685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1318f2d822'
down_revision = 'd1f5dfae3cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_chapter', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_column('is_chapter')
        batch_op.drop_column('chapter_order')

    # ### end Alembic commands ###
